services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: typescript_batch
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # 管理UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - mysql
      - rabbitmq
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - .env

volumes:
  mysql-data:
